#!/bin/bash -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


# Sanity check
if [ -z "$WATCOM" ]; then
  echo '$WATCOM not set.' >&2
  exit 1
fi

if [ -z "$(which wcl)" ]; then
  echo "Watcom's wcl not found in \$PATH" >&2
  exit 1
fi


# Build tools if needed
(
  cd "$SCRIPTDIR/tools"
  ./build.sh
)


# Parse command line
IGNORE=""
LOOP=""
COMPRESS=""
while getopts :ilc OPT; do 
  case $OPT in
    i)
      IGNORE=-i
      ;;
    l)
      LOOP="-dLOOP_SONG=1"
      ;;
    c)
      COMPRESS="y"
      ;;
  esac
done

shift $((OPTIND-1))

function usage() {
  cat >&2 <<EOF
usage: $(basename "$0") [-i] [-l] [-c] <rad-file> <out-file>
  -i  ignore .rad file validation errors
  -l  make player loop song
  -c  compress created executable
EOF
  exit 1
}

[[ $# < 2 ]] && usage


# Do the actual work
TMPDIR="$(mktemp -d)"
"$SCRIPTDIR/tools/prepare" $IGNORE "$1" "$TMPDIR/songdata.h"
wcl -bcl=dos -lr -ox $LOOP -i="$SCRIPTDIR/ext" -i="$TMPDIR" -fe="$TMPDIR/play.exe" -mh "$SCRIPTDIR/player/main.cpp"
[ "$COMPRESS" == "y" ] && "$SCRIPTDIR/ext/upx" --ultra-brute --8086 "$TMPDIR/play.exe"
cp "$TMPDIR/play.exe" "$2"
rm -rf "$TMPDIR"
